<?php

namespace lib\Services;

use App\Entities\Page;
use App\Entities\PageContent;
use app\Services\PageService;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;
use function Amp\ByteStream\parseLineDelimitedJson;

class PageServiceTest extends CIUnitTestCase
{
    use DatabaseTestTrait;

    protected $migrate = true;
    protected $migrateOnce = true;

    protected $namespace = null;

    private ?PageService $pages;

    public function newPage(): Page
    {
        $page = new Page([
            'contents' => [
                    new PageContent([
                    'title' => 'TestPageService',
                    'lang' => 'en',
                    'slug' => 'test-page-service',
                    'description' => 'A Test page to test the TestPageService class',
                    'tags' => 'test,page',
                    'contents' => 'these are test contents for the test page'
                ]),
             ]
        ]);
        return $page;
    }

    public function setUp(): void {
        parent::setUp();

        $this->pages = \Tests\Support\Config\Services::pages();

    }

    public function tearDown(): void
    {
        $this->pages = null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testSaveInsert(): void
    {
        $page = $this->newPage();
        $this->assertTrue($page->hasContents());
        $result = $this->pages->save($page);
        $this->assertIsInt($page->id);
        $this->assertTrue($page->hasContents());
        $this->assertIsInt($page->getContent('en')->id);
    }

    public function testSaveUpdate(): void
    {
        $page = $this->newPage();
        $this->pages->save($page);
        $this->assertIsInt($page->id);
        $page_content = $page->getContent('en');
        $page_content->title = 'updated title';
        $this->pages->save($page);
        $updated = $this->pages->get($page->id);
        $this->assertNotNull($updated);
        $this->assertEquals($page_content->title, $updated->getContent('en')->title);
    }

    public function testGet(): void
    {
        $page = $this->newPage();
        $this->pages->save($page);
        $this->assertIsInt($page->id);
        $saved = $this->pages->get($page->id);
        $this->assertEquals($page->id, $saved->id);
        $this->assertTrue($page->hasContents());
        $this->assertIsList($page->contents);
    }

    public function testGetNonExisting(): void
    {
        $this->assertNull($this->pages->get(0));
    }

    public function testDelete(): void
    {
        $page = $this->newPage();
        $this->pages->save($page);
        $this->assertIsInt($page->id);

        $found = $this->pages->get($page->id);
        $this->assertNotNull($found);

        $this->pages->delete($found->id);
        $deleted = $this->pages->get($page->id);
        $this->assertNull($deleted);
    }

    public function testDeleteNonExisting(): void
    {
        $this->assertFalse($this->pages->delete(0));
    }

    public function testSearch(): void
    {
        $result = $this->pages->search(['title' => ''])->getResult();
        $this->assertIsArray($result);
    }
}
