image: mkuettel/phpci:8.3-apache

cache:
  paths:
    - vendor/

before_script:
  - cp /usr/local/etc/php/php.ini{-development,}
  - echo 'xdebug.mode=coverage' >> /usr/local/etc/php/php.ini
  - cp env-ci .env
  - php /composer.phar install


variables:
  MYSQL_DATABASE: "ci4_services_test"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"

stages:
  - build
  - test
  - pkg
  - deploy

build-job:
  stage: build
  script:
    - echo "Building"
    - echo "Nothing to do ... "

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text --colors=never

unit-test-job-mysql:
  stage: test
  services:
    - mysql:5.7
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sed 's/\(name="database.tests.DBDriver" value="\)[^"]*/\1MySQLi/' < phpunit.xml.dist > phpunit.xml
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never

lint-test-job:
  stage: test
  allow_failure: true
  script:
    - echo "Linting code... This will take about 10 seconds."
    - vendor/bin/phpcs

package-job:
  stage: pkg
  script:
  - php /composer.phar install --no-dev
  - php /composer.phar dump-autoload
  - tar cvzf codeigniter4-services-$(git rev-parse HEAD).tar.gz src vendor LICENSE README.md env

deploy-job:
  stage: deploy
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "production"
  script:
    - echo "Don't know how to deploy"
